import type { editor } from "monaco-editor";

export const ELECTRODB_THEME_NAME = "electrodb";

export const electrodbTheme: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  colors: {
    focusBorder: "#388bfd",
    foreground: "#c9d1d9",
    descriptionForeground: "#8b949e",
    errorForeground: "#f85149",
    "editor.foreground": "#c9d1d9",
    "editor.background": "#0d1117",
    "scrollbar.shadow": "#0d1117",
    "scrollbarSlider.background": "#484F5833",
    "scrollbarSlider.hoverBackground": "#484F5844",
    "scrollbarSlider.activeBackground": "#484F5888",
    "editorOverviewRuler.border": "#0d1117",
  },
  rules: [
    { token: "type", foreground: "#4781b7", fontStyle: "bold" },
    { token: "number", foreground: "#ffc107" },
    { token: "regexp", foreground: "#ffc107" },
    { token: "boolean", foreground: "#ffc107" },
    { token: "comment", foreground: "#8b949e" },
    { token: "punctuation.definition.comment", foreground: "#8b949e" },
    { token: "string.comment", foreground: "#8b949e" },
    { token: "constant", foreground: "#79c0ff" },
    { token: "entity.name.constant", foreground: "#79c0ff" },
    { token: "variable.other.constant", foreground: "#79c0ff" },
    { token: "variable.language", foreground: "#79c0ff" },
    { token: "entity", foreground: "#79c0ff" },
    { token: "entity.name", foreground: "#ffa657" },
    { token: "meta.export.default", foreground: "#ffa657" },
    { token: "meta.definition.variable", foreground: "#ffa657" },
    { token: "variable.parameter.function", foreground: "#ffc107" },
    { token: "variable.parameter", foreground: "#f08d39" },
    { token: "parameter.variable", foreground: "#f08d39" },
    { token: "meta.function.parameter variable", foreground: "#f08d39" },
    { token: "meta.jsx.children", foreground: "#c9d1d9" },
    { token: "meta.block", foreground: "#c9d1d9" },
    { token: "meta.tag.attributes", foreground: "#c9d1d9" },
    { token: "meta.object.member", foreground: "#c9d1d9" },
    { token: "meta.embedded.expression", foreground: "#c9d1d9" },
    { token: "entity.name.function", foreground: "#d2a8ff" },
    { token: "entity.name.tag", foreground: "#7ee787" },
    { token: "support.class.component", foreground: "#7ee787" },
    { token: "keyword", foreground: "#ffc107" },
    { token: "storage", foreground: "#4781b7" },
    { token: "storage.type", foreground: "#4781b7" },
    { token: "storage.modifier.package", foreground: "#c9d1d9" },
    { token: "storage.modifier.import", foreground: "#c9d1d9" },
    { token: "string", foreground: "#79c0ff" },
    { token: "punctuation.definition.string", foreground: "#79c0ff" },
    { token: "string punctuation.section.embedded source", foreground: "#79c0ff" },
    { token: "support", foreground: "#79c0ff" },
    { token: "meta.property-name", foreground: "#79c0ff" },
    { token: "variable", foreground: "#ffa657" },
    { token: "variable.other", foreground: "#c9d1d9" },
    { token: "invalid.broken", foreground: "#ffa198", fontStyle: "italic" },
    { token: "invalid.deprecated", foreground: "#ffa198", fontStyle: "italic" },
    { token: "invalid.illegal", foreground: "#ffa198", fontStyle: "italic" },
    { token: "invalid.unimplemented", foreground: "#ffa198", fontStyle: "italic" },
    { token: "message.error", foreground: "#ffa198" },
    { token: "string source", foreground: "#c9d1d9" },
    { token: "string variable", foreground: "#79c0ff" },
    { token: "source.regexp", foreground: "#79c0ff" },
    { token: "string.regexp", foreground: "#79c0ff" },
    { token: "string.regexp.character-class", foreground: "#79c0ff" },
    { token: "string.regexp constant.character.escape", foreground: "#7ee787", fontStyle: "bold" },
    { token: "support.constant", foreground: "#79c0ff" },
    { token: "support.variable", foreground: "#79c0ff" },
    { token: "meta.module-reference", foreground: "#79c0ff" },
    { token: "markup.heading", foreground: "#79c0ff", fontStyle: "bold" },
    { token: "markup.quote", foreground: "#7ee787" },
    { token: "markup.italic", foreground: "#c9d1d9", fontStyle: "italic" },
    { token: "markup.bold", foreground: "#c9d1d9", fontStyle: "bold" },
    { token: "markup.raw", foreground: "#79c0ff" },
    { token: "brackethighlighter.tag", foreground: "#8b949e" },
    { token: "brackethighlighter.curly", foreground: "#8b949e" },
    { token: "brackethighlighter.round", foreground: "#8b949e" },
    { token: "brackethighlighter.square", foreground: "#8b949e" },
    { token: "brackethighlighter.angle", foreground: "#8b949e" },
    { token: "brackethighlighter.quote", foreground: "#8b949e" },
    { token: "brackethighlighter.unmatched", foreground: "#ffa198" },
    { token: "constant.other.reference.link", foreground: "#79c0ff", fontStyle: "underline" },
    { token: "string.other.link", foreground: "#79c0ff", fontStyle: "underline" },
  ],
};
