import { useEffect, useMemo, useRef, useState } from "react";
import Prism from "prismjs";
import "prismjs/components/prism-json";
import type { OutputItem, QueryOrigin } from "../lib/types";

/** A request to scroll a params block into view; nonce retriggers repeats */
export interface DisplayFocus {
  index: number;
  nonce: number;
}

function RevealSourceIcon() {
  return (
    <svg
      viewBox="0 0 24 24"
      width="14"
      height="14"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      aria-hidden="true"
    >
      <circle cx="11" cy="11" r="7" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function ParamsBlock({
  label,
  json,
  origin,
  onRevealSource,
}: {
  label: string | null;
  json: string;
  origin?: QueryOrigin;
  onRevealSource(origin: QueryOrigin): void;
}) {
  const html = useMemo(
    () => Prism.highlight(json, Prism.languages.json, "json"),
    [json],
  );
  return (
    <>
      <hr />
      <div className="output-item-header">
        {label ? (
          // Labels are generated by the playground bundle (e.g. "Queries the
          // access pattern <b>Backlog</b>…") and are trusted markup.
          <div
            className="output-item-label"
            dangerouslySetInnerHTML={{ __html: label }}
          />
        ) : null}
        {origin ? (
          <button
            type="button"
            className="reveal-source"
            title={`Show the query in ${origin.file}:${origin.line}`}
            aria-label={`Show the query in ${origin.file}, line ${origin.line}`}
            onClick={() => onRevealSource(origin)}
          >
            <RevealSourceIcon />
          </button>
        ) : null}
      </div>
      <pre className="language-json">
        <code
          className="language-json"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      </pre>
    </>
  );
}

function MessageBlock({ type, html }: { type: "info" | "error"; html: string }) {
  return (
    <>
      <hr />
      {type === "error" ? <h2>Query Error</h2> : null}
      <div
        className={`${type} message`}
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </>
  );
}

export interface DisplayProps {
  items: OutputItem[];
  focus: DisplayFocus | null;
  onRevealSource(origin: QueryOrigin): void;
}

export function Display({ items, focus, onRevealSource }: DisplayProps) {
  const itemRefs = useRef(new Map<number, HTMLDivElement>());
  const [flashIndex, setFlashIndex] = useState<number | null>(null);

  useEffect(() => {
    if (!focus) {
      return;
    }
    const element = itemRefs.current.get(focus.index);
    if (!element) {
      return;
    }
    element.scrollIntoView({ behavior: "smooth", block: "start" });
    setFlashIndex(focus.index);
    const timer = window.setTimeout(() => setFlashIndex(null), 1600);
    return () => window.clearTimeout(timer);
  }, [focus]);

  return (
    <div className="display-wrapper">
      {items.map((item, index) => (
        <div
          key={index}
          className={`output-item${flashIndex === index ? " focused" : ""}`}
          ref={(element) => {
            if (element) {
              itemRefs.current.set(index, element);
            } else {
              itemRefs.current.delete(index);
            }
          }}
        >
          {item.kind === "params" ? (
            <ParamsBlock
              label={item.label}
              json={item.json}
              origin={item.origin}
              onRevealSource={onRevealSource}
            />
          ) : (
            <MessageBlock type={item.type} html={item.html} />
          )}
        </div>
      ))}
    </div>
  );
}
