import { useMemo } from "react";
import Prism from "prismjs";
import "prismjs/components/prism-json";
import type { OutputItem } from "../lib/types";

function ParamsBlock({ label, json }: { label: string | null; json: string }) {
  const html = useMemo(
    () => Prism.highlight(json, Prism.languages.json, "json"),
    [json],
  );
  return (
    <div className="output-item">
      <hr />
      {label ? (
        // Labels are generated by the playground bundle (e.g. "Queries the
        // access pattern <b>Backlog</b>…") and are trusted markup.
        <div dangerouslySetInnerHTML={{ __html: label }} />
      ) : null}
      <pre className="language-json">
        <code
          className="language-json"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      </pre>
    </div>
  );
}

function MessageBlock({ type, html }: { type: "info" | "error"; html: string }) {
  return (
    <div className="output-item">
      <hr />
      {type === "error" ? <h2>Query Error</h2> : null}
      <div
        className={`${type} message`}
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}

export function Display({ items }: { items: OutputItem[] }) {
  return (
    <div className="display-wrapper">
      {items.map((item, index) =>
        item.kind === "params" ? (
          <ParamsBlock key={index} label={item.label} json={item.json} />
        ) : (
          <MessageBlock key={index} type={item.type} html={item.html} />
        ),
      )}
    </div>
  );
}
